
// VDATGRLS_DNI

// VDATGRLS_SERIE
// VDATGRLS_NOMBRES
// VDATGRLS_APELLPAT
// VDATGRLS_APELLMAT
// DDATGRLS_FECHNAC
// CUBIGEO_NACE
// CUBIGEO_VIVE
// VDATGRLS_DIRECCION
// CSEXO_CODIGO
// CESTCIV_CODIGO
// VDATGRLS_TELEFONO